exports.CONFIG_CODES = Object.freeze({
	PAYMENT_NUMBER_OF_ATTEMPTS: "PAYMENT_NUMBER_OF_ATTEMPTS",
	PAYMENT_FREQUENCY_OF_ATTEMPTS_HOURS: "PAYMENT_FREQUENCY_OF_ATTEMPTS_HOURS",
	SHIPMENT_FAIL_MAX: "SHIPMENT_FAIL_MAX",
	SHIPMENT_FAIL_FREQUENCY: "SHIPMENT_FAIL_FREQUENCY",
	SHIPMENT_FAIL_UOM: "SHIPMENT_FAIL_UOM",
	API_PAGO_USER: "API_PAGO_USER",
	API_PAGO_PASS: "API_PAGO_PASS",
	RENEWAL_DAYS: "RENEWAL_DAYS",
	RENEWAL_NOTICE_RETRIES: "RENEWAL_NOTICE_RETRIES",
	RENEWAL_RETRIES: "RENEWAL_RETRIES",
	RENEWAL_SUCCESS_RETRIES: "RENEWAL_SUCCESS_RETRIES",
	DIGEVO_SPEED: "DIGEVO_SPEED",
});
